config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'
  resources :artists do
    resources :songs, only: [:new, :create]
  end
  resources :songs, only: [:show]
  resources :playlists, only: [:index, :new, :create, :show, :edit, :update]
  get '/auth/spotify/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true
 
  has_many :songs
end

app/models/model.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
  
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
  
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create_from_auth(auth)
      User.find_or_create_by(
        provider: auth["provider"],
        uid: auth["info"]["id"],
        name: auth["info"]["display_name"]
      )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

private

  def set_artist
    @artist = Artist.find(params[:id ])
  end

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to playlists_path
    end
  end

  def destroy
    session.clear
    redirect_to playlists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
  end

private

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <%= render partial: "shared/errors", locals: { target: @artist } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<%= link_to "New artist", new_artist_path %>

<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<%= link_to "Edit", edit_artist_path(@artist) %>
<%= link_to "Delete", artist_path(@artist), method: :delete %>
<%= link_to "New song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <h3>Welcome, <%= current_user.name %></h3>
  <%= link_to "Sign out", logout_path, method: :delete %>
<% else %>
  <%= link_to "Sign in with Spotify", "/auth/spotify" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render partial: "form" %>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Add a new song for <%= @artist.name %></p>
<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= link_to @song.artist.name, artist_path(@song.artist) %>